"""empty message

Revision ID: dd2d1ee7627e
Revises: 
Create Date: 2021-03-15 23:19:07.610133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2d1ee7627e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'gender',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('actors', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('movies', 'release_date',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('movies', 'title',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'title',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('movies', 'release_date',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('actors', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('actors', 'gender',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
